version: "3"
services:
  object-cache:
    image: memcached
    container_name: object-cache
    ports:
      - 11211:11211
  db:
    image: postgres
    container_name: pgsql
    environment:
      - foo=foo
      - bar=bar
    volumes:
      - ./sql/:/opt/sql
      - ./postgres-data:/var/lib/postgresql/data
#      - ./sql/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  web:
    #  replaced image with build for development
    image: benit/debian-web
    environment:
      - http_proxy
      - https_proxy
    links:
      - db:database
      - object-cache:object-cache
    container_name: web
    depends_on:
      - db
      - object-cache
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./data/:/opt/data